Remove windows build since it does not compile
```
error[E0425]: cannot find value `STDOUT_FILENO` in crate `libc`
   --> src\md\printer.rs:322:33
    |
322 |     unsafe { libc::isatty(libc::STDOUT_FILENO) == 0 }
    |                                 ^^^^^^^^^^^^^ not found in `libc`
```